### ISSUE TITLE
[Android] 프로젝트 기본 설정

### ISSUE THREAD

**Issue by banjjak2** [junseokseo9306/airbnb#1]
제목: 프로젝트 기본 설정
---

## 💡 issue
- 필수 라이브러리 추가
- 앱 전체 스타일 정의 (폰트, 텍스트, 아이콘 등)

## 📝 todo
- [x] 사용할 라이브러리 의존성 추가
- [x] 앱 전체 스타일 정의
  - [x] 폰트 설정
  - [x] 텍스트 스타일 정의
- [x] AppBar 구현
