### ISSUE TITLE
[Android] 기본 UI 컴포넌트 구현

### ISSUE THREAD

**Issue by banjjak2** [junseokseo9306/airbnb#2]
제목: 기본 UI 컴포넌트 구현
---

## 💡 issue
- 앱 전체에서 사용될 UI 컴포넌트 구현

## 📝 todo
- [x] 바텀 내비게이션 설정
- [x] 메인화면 구현
- [x] tmap api에서 시간 가져오기
- [x] compose 리사이클러뷰 구현 
- [x] customView에 데이터 적용하기

**Comment by junseokseo9306** [comment]
1. Gson, Moshi 는 dataClass를 알아서 Json 객체로 Encoding을 해주었습니다. 하지만, kotlin-Serialization은 reflection기능이 없어 자동으로 converting이 되지 않음.


---
## 해결방법
Kotlin-Serialization 을 encoding하기 위해서 body로 보낼 dataClass에 @Serialization 어노테이션을 붙어주었음

**Comment by junseokseo9306** [comment]
Tmap api로 자신의 위치에서 거리 가져올때 속도가 너무 느리기에 리사이클러뷰가 바인딩 된 후에 값을 가지고 오게 됨.

- 문제점 : tmap api는 비동기로 요청을 할 수 없음. 한번에 여러번 요청을 하면 error을 내어줌

**Comment by junseokseo9306** [comment]
## kotlin flow 사용시 문제점

- 에러 : repository에서 flow collect와 emit이 함께 있을 경우 emit이 먼저 실행되고 flow의 collect가 실행됨

```

override fun getTime(tmapRequest: TmapRequest): Flow<Tmap> {
val tmapTime = MutableStateFlow<Tmap>(Tmap(0))

tmapDataSource.getTime(tmapRequest).buffer().onEach { tmapDto ->
            Log.d("DataRepository", "${tmapDto.toTmap().totalMinute}")
            tmapTime.emit(tmapDto.toTmap())
        }.launchIn(CoroutineScope(Dispatchers.Main.immediate))

return flow { emit(tmapTime.value) }

}
```


---

## 해결 

- 현재 : return 을 flow builder, MutableStateFlow가 아닌 MutableSharedFlow로 변경 
- shareFlow에는 replay = 1, onBufferOverflow = BufferOverflow.DROP_OLDEST추가

```
val tmapTime = MutableSharedFlow<Tmap>(replay = 1, onBufferOverflow = BufferOverflow.DROP_OLDEST)

        tmapDataSource.getTime(tmapRequest).buffer().onEach { tmapDto ->
            Log.d("DataRepository", "${tmapDto.toTmap().totalMinute}")
            tmapTime.emit(tmapDto.toTmap())
        }.launchIn(CoroutineScope(Dispatchers.Main.immediate))

```

**Comment by junseokseo9306** [comment]
## 문제 발생

- customView를 선언한 클래스에서 set~~ function이 작동하지 않는 현상

**Comment by junseokseo9306** [comment]
## Context로 Color 가져올때 Require M 버전 요구시


- 해결책
- contextCompat사용하여 가져오기

**Comment by junseokseo9306** [comment]
## BroadCast Receiver + PendingIntent 를 통한 백그라운드 작업 시 BroadCastReceiver에 계속 null값이 OnReceive되는 문제

- 문제점 계속 broadCastReceiver에 null값이 들어와서 앱내 오류 생성됨

- 해결책 : broadCastReceiver안에 선언된 메서드들을 null타입으로 바꾸어 주어 문제 해결 (처음에는 null타입이지만 LocationRequest에 정의한 시간이 지난뒤에 좌표를 가지고 오는것을 확인할 수 있었음)

```

LocationResult.extractResult(intent)?.let { locationResult ->
                myLatitude = locationResult.lastLocation.latitude
                myLongitude = locationResult.lastLocation.longitude
                Log.d("broadCastReceiver", "latitude: $myLatitude, longitude: $myLongitude")
            }

```

---
## S버전 이후에서는 PendingIntent Flag의 사용이 바뀜

- 이전 버전은 FLAG_UPDATE_CURRENT 와 같은 플래그를 사용하였지만

- 이후 버전은 FLAG_MUTABLE or FLAG_IMMUTABLE 을 사용해 주어야 한다. 
- 두가지의 차이점은 찾아볼 예정
