### ISSUE TITLE
[BE] Reservation 도메인 작성

### ISSUE THREAD

**Issue by ffinn92** [junseokseo9306/airbnb#7]
제목: [Feat] Reservation 도메인 및 Entity 작성
---

## 💡 issue
- 예약관련 (reservation, user, wishlist) 도메인 및 Entity 작성

## 📝 todo
* [x] domain 패키지 내 클래스 작성
* [x] dto 패키지 내 클래스 작성
* [x] web 패키지 내 클래스 작성
