### ISSUE TITLE
[Android] 네트워크 모듈 생성

### ISSUE THREAD

**Issue by junseokseo9306** [junseokseo9306/airbnb#8]
제목: android 네트워크 모듈 생성
---

## 💡 issue
이슈 작성

## 📝 todo
- [x] 네트워크 레이어 생성
- [x] 힐트 모듈 생성
- [x] 데이터 레이어 생성
- [x] Dto 생성

**Comment by junseokseo9306** [comment]
# 장애발생

![스크린샷 2022-05-24 23 06 37](https://user-images.githubusercontent.com/83396157/170060854-47c44949-27f3-4879-8c1a-769490334a27.png)

## 해결방법
- Hilt Module Application package명이 잘못되어있었음

**Comment by junseokseo9306** [comment]
Kotlin Serialization 적용시 주의할점

- Gradle에 classPath 기입
- gradle에 kotlin-serialization-runtime 추가 필요

**Comment by junseokseo9306** [comment]
Kotlin Serialization Runtime 추가시 오류 발생

![image](https://user-images.githubusercontent.com/83396157/170073786-725adfbc-7ae2-4f7d-90e7-4b0aec20442d.png)

- runtime implementation 제거
- 이후 다시 빌드 후 정상작동
